### ISSUE TITLE
slight adjustment in wording could help

### ISSUE THREAD

**Issue by bubbaspaarx** [learn-co-curriculum/react-component-updating-lab#1]
this

> shouldComponentUpdate takes in two arguments, the next props and state from the potential update. We also have access to our current props and state, allowing us to write comparison like the following:

to this

> shouldComponentUpdate takes in two arguments, the next props (nextProps) and state (nextState) from the potential update. We also have access to our current props and state, allowing us to write comparison like the following:

**Comment by bubbaspaarx** [comment]
@timothylevi

**Comment by MiriamPeskowitz** [comment]
Objectives/3
Practice the using shouldComponentUpdate and componentDidUpdate. -- delete "the"

**Comment by maxwellbenton** [comment]
Hi @bubbaspaarx and @MiriamPeskowitz,

Thank you for spotting this issue and providing feedback.

We have updated the `shouldComponentUpdate` and Objectives sections of this readme and believe your issues have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
